In [8]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("\nVertical stacking:\n", np.vstack((A, B)))

print("\nHorizontal stacking:\n", np.hstack((A, B)))

C = [5, 6]
print("\nColumn stacking:\n", np.column_stack((A, C)))

print("\nConcatenating to 2nd axis:\n", np.concatenate((A, B), 1))


Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


In [11]:
import numpy as np

A = np.array([
    [6, 1, 1],
    [4, -2, 5],
    [2, 8, 7]
])

print("\nRank of A: ", np.linalg.matrix_rank(A))

print("\nTrace of A: ", np.trace(A))

print("\nDeterminant of A: ", np.linalg.det(A))

print("\nInverse of A: ", np.linalg.inv(A))

print("\nMatrix A raised to power 3:\n", np.linalg.matrix_power(A, 3))


Rank of A:  3

Trace of A:  11

Determinant of A:  -306.0

Inverse of A:  [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]
