# Lists and Arrays

In [5]:
import numpy as np

np.__version__

'1.16.4'

In [8]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Array is of type: ", type(arr))

print("No of dimensions: ", arr.ndim)

print("Shape of array: ", arr.shape)

print("Size of array: ", arr.size)

print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [10]:
A = np.array([
    [1, 2, 4],
    [5, 8, 7]
], dtype = 'float')

print("\nArray created using passed list: \n", A)

B = np.array((1, 3, 2))
print("\nArray created using passed tuple: \n", B)

C = np.zeros(5)
print("\nArray initialized with all zeros: \n", C)

D = np.zeros([5, 5])
print("\n Array initialized with all zeros: \n", D)

E = np.ones([5, 5])
print("\n Array initialized with all ones: \n", E)

F = np.random.random([5, 5])
print("\n Array initialized with all randoms: \n", F)


Array created using passed list: 
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple: 
 [1 3 2]

Array initialized with all zeros: 
 [0. 0. 0. 0. 0.]

 Array initialized with all zeros: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 Array initialized with all ones: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 Array initialized with all randoms: 
 [[0.64659605 0.49548185 0.84817873 0.33611089 0.95804172]
 [0.10759215 0.74942157 0.7296002  0.35549937 0.84274053]
 [0.51639052 0.20095072 0.97326726 0.88970329 0.42287097]
 [0.18771118 0.0228413  0.20073189 0.74063503 0.95171194]
 [0.7895909  0.53226116 0.38458113 0.33465847 0.8583316 ]]


In [11]:
A = np.array([1, 2, 3, 4])
print("\nAdding 1 to every element: ", A + 1)

print("\nSubtracking 3 from each element: ", A - 3)

print("\nMultiplying each element by 10: ", A * 10)

print("\nSquaring each element: ", A**2)

A *= 2
print("\nDoubled each element of original array: ", A)

B = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\nOriginal array: \n", B)
print("\nTranspose of array: \n", B.T)


Adding 1 to every element:  [2 3 4 5]

Subtracking 3 from each element:  [-2 -1  0  1]

Multiplying each element by 10:  [10 20 30 40]

Squaring each element:  [ 1  4  9 16]

Doubled each element of original array:  [2 4 6 8]

Original array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of array: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("\nVertical stacking:\n", np.vstack((A, B)))

print("\nHorizontal stacking:\n", np.hstack((A, B)))

C = [5, 6]
print("\nColumn stacking:\n", np.column_stack((A, C)))

print("\nConcatenating to 2nd axis:\n", np.concatenate((A, B), 1))


Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]
