# Matrix

In [1]:
import numpy as np

In [2]:
x = np.array([
    [1, 2],
    [3, 4]
])

y = np.array([
    [1, 2],
    [3, 4]
])

In [3]:
np.add(x, y)

array([[2, 4],
       [6, 8]])

In [4]:
np.subtract(x, y)

array([[0, 0],
       [0, 0]])

In [10]:
# Element wise matrix multiplication
np.multiply(x, y)

array([[ 1,  4],
       [ 9, 16]])

In [9]:
np.divide(x, y)

array([[1., 1.],
       [1., 1.]])

In [12]:
# Matrix multiplication rather than element wise multiplication
np.dot(x, y)

array([[ 7, 10],
       [15, 22]])