Arrays in Numpy

In [3]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Array is of type: ", type(arr))

print("No of dimensions: ", arr.ndim)

print("Shape of array: ", arr.shape)

print("Size of array: ", arr.size)

print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [17]:
import numpy as np

A = np.array([
    [1, 2, 4],
    [5, 8, 7]
], dtype = 'float')

print("\nArray created using passed list: \n", A)

B = np.array((1, 3, 2))
print("\nArray created using passed tuple: \n", B)

C = np.zeros(5)
print("\nArray initialized with all zeros: \n", C)

D = np.zeros([5, 5])
print("\n Array initialized with all zeros: \n", D)

E = np.ones([5, 5])
print("\n Array initialized with all ones: \n", E)

F = np.random.random([5, 5])
print("\n Array initialized with all randoms: \n", F)


Array created using passed list: 
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple: 
 [1 3 2]

Array initialized with all zeros: 
 [0. 0. 0. 0. 0.]

 Array initialized with all zeros: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 Array initialized with all ones: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 Array initialized with all randoms: 
 [[0.23175901 0.59648284 0.57955601 0.88039001 0.41424681]
 [0.10746739 0.46331229 0.83101303 0.87672067 0.48254436]
 [0.70228743 0.98196419 0.0846471  0.55543233 0.35450656]
 [0.17996194 0.21068395 0.09717479 0.95313781 0.63070908]
 [0.98631634 0.46474355 0.13607716 0.88618986 0.87086897]]


In [23]:
import numpy as np

A = np.arange(0, 30, 5)
print("\n A sequential array with steps of 5: \n", A)

B = np.full((3, 3), 6, dtype = 'complex')
print('\n An array initialized with all 6s. with array type is complex: \n', B)

C = np.linspace(0, 5, 10)
print("\n A sequence array with 10 values between 0 and 5:\n", C)

D = np.array([
    [1, 2, 3, 4],
    [5, 2, 4, 2],
    [1, 2, 0, 1]
])

E = D.reshape(2, 2, 3)
print("\n Original array: \n", D)
print("\n Reshaped array: \n", E)

F = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

G = F.flatten()
print("\n Original array: \n", F)
print("\n Flatten array: \n", G)


 A sequential array with steps of 5: 
 [ 0  5 10 15 20 25]

 An array initialized with all 6s. with array type is complex: 
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

 A sequence array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

 Original array: 
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Reshaped array: 
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

 Original array: 
 [[1 2 3]
 [4 5 6]]

 Flatten array: 
 [1 2 3 4 5 6]


In [26]:
import numpy as np

A = np.array([
    [-1, 2, 0, 4],
    [4, -0.5, 6, 0],
    [2.6, 0, 7, 8],
    [3, -7, 4, 2.0]
])

B = A[:2, ::2]
print("\nArray with first 2 rows and alternate columns(0 and 2): \n", B)

C = A[
    [0, 1, 2, 3],
    [3, 2, 1, 0]
]
print("\nElements at indices (0, 3), (1, 2), (2, 1), (3, 0):\n", C)



Array with first 2 rows and alternate columns(0 and 2): 
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1), (3, 0):
 [4. 6. 0. 3.]


In [34]:
import numpy as np

A = np.array([1, 2, 3, 4])
print("\nAdding 1 to every element: ", A + 1)

print("\nSubtracking 3 from each element: ", A - 3)

print("\nMultiplying each element by 10: ", A * 10)

print("\nSquaring each element: ", A**2)

A *= 2
print("\nDoubled each element of original array: ", A)

B = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\nOriginal array: \n", B)
print("\nTranspose of array: \n", B.T)


Adding 1 to every element:  [2 3 4 5]

Subtracking 3 from each element:  [-2 -1  0  1]

Multiplying each element by 10:  [10 20 30 40]

Squaring each element:  [ 1  4  9 16]

Doubled each element of original array:  [2 4 6 8]

Original array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of array: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [38]:
import numpy as np

A = np.array([
    [1, 4, 2],
    [3, 4, 6],
    [0, -1, 5]
])
print("\nArray elements in sorted order:\n", np.sort(A, axis = None))

print("\nRow-wise sorted array:\n", np.sort(A, axis = 1))

print("\nColumn-wise sorted by applying merge-sort:\n", np.sort(A, axis = 0, kind = 'mergesort'))

print("\n")


Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]

Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]

Column-wise sorted by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]
